./logs/access.log {
  daily
  rotate 30
  size 10M
  create 0640 root root

  dateext
  dateformat .%Y-%m-%d_%H

  compress
  delaycompress

  missingok
  notifempty

  sharedscripts
  postrotate
    docker kill --signal=USR1 traefik
  endscript
}
