global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: false

entryPoints:
  http:
    address: :80
    forwardedHeaders:
      trustedIPs:
        - 127.0.0.1/32
        - 192.168.0.0/16
        - 172.16.0.0/12
        - 10.0.0.0/8
        # cloudflare IPv4
        - 103.21.244.0/22
        - 103.22.200.0/22
        - 103.31.4.0/22
        - 104.16.0.0/13
        - 104.24.0.0/14
        - 108.162.192.0/18
        - 131.0.72.0/22
        - 141.101.64.0/18
        - 162.158.0.0/15
        - 172.64.0.0/13
        - 173.245.48.0/20
        - 188.114.96.0/20
        - 190.93.240.0/20
        - 197.234.240.0/22
        - 198.41.128.0/17
        # cloudflare IPv6
        - 2400:cb00::/32
        - 2606:4700::/32
        - 2803:f800::/32
        - 2405:b500::/32
        - 2405:8100::/32
        - 2a06:98c0::/29
        - 2c0f:f248::/32
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: :443
    http:
      tls: {}
    forwardedHeaders:
      trustedIPs:
        - 127.0.0.1/32
        - 192.168.0.0/16
        - 172.16.0.0/12
        - 10.0.0.0/8
        # cloudflare IPv4
        - 103.21.244.0/22
        - 103.22.200.0/22
        - 103.31.4.0/22
        - 104.16.0.0/13
        - 104.24.0.0/14
        - 108.162.192.0/18
        - 131.0.72.0/22
        - 141.101.64.0/18
        - 162.158.0.0/15
        - 172.64.0.0/13
        - 173.245.48.0/20
        - 188.114.96.0/20
        - 190.93.240.0/20
        - 197.234.240.0/22
        - 198.41.128.0/17
        # cloudflare IPv6
        - 2400:cb00::/32
        - 2606:4700::/32
        - 2803:f800::/32
        - 2405:b500::/32
        - 2405:8100::/32
        - 2a06:98c0::/29
        - 2c0f:f248::/32
    http3:
      advertisedPort: 443

providers:
  docker:
    endpoint: 'tcp://traefik-dockerproxy:2375'
    exposedByDefault: false
    network: proxy
  file:
    directory: /configs
    watch: true

certificatesResolvers:
  staging:
    acme:
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      email: cert@example.com
      storage: acme.json
      httpChallenge:
        entryPoint: http

  production:
    acme:
      caServer: https://acme-v02.api.letsencrypt.org/directory
      email: cert@example.com
      storage: acme.json
      httpChallenge:
        entryPoint: http

  letsencrypt:
    acme:
      email: cert@example.com
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - 1.1.1.1:53
          - 1.0.0.1:53

serversTransport:
  insecureSkipVerify: false

log:
  level: ERROR # INFO
  filePath: /logs/traefik.log
  format: common # json
  maxSize: 5
  maxBackups: 10
  # maxAge: 30
  compress: true

accesslog:
  filePath: /logs/access.log
  format: common # json
  bufferingSize: 2 # 50
  filters:
    statusCodes:
      - 200-299
      - 400-599
  fields:
    headers:
      names:
        User-Agent: keep
