global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: false

entryPoints:
  http:
    address: :8080 # :80 # TODO: replace
    forwardedHeaders:
      trustedIPs: &ip_ranges
        - 127.0.0.1/32
        - 192.168.0.0/16
        - 172.16.0.0/12
        - 10.0.0.0/8
        # cloudflareIPs
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: :8443 # :443 # TODO: replace
    http:
      tls: {}
    forwardedHeaders:
      trustedIPs: *ip_ranges
    http3:
      advertisedPort: 8443 # 443 # TODO: replace

providers:
  docker:
    endpoint: 'tcp://traefik-dockerproxy:2375'
    exposedByDefault: false
    network: proxy
    constraints: 'Label(`traefik.mode`, `testing`)' # TODO: remove
  file:
    directory: /configs
    watch: true

certificatesResolvers:
  staging:
    acme:
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      email: example@gmail.com
      storage: acme.json
      httpChallenge:
        entryPoint: http

  production:
    acme:
      caServer: https://acme-v02.api.letsencrypt.org/directory
      email: example@gmail.com
      storage: acme.json
      httpChallenge:
        entryPoint: http

  letsencrypt:
    acme:
      email: example@gmail.com
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - 1.1.1.1:53
          - 1.0.0.1:53

serversTransport:
  insecureSkipVerify: false

log:
  level: ERROR
  filePath: /logs/traefik.log
  format: common # json
  maxSize: 5
  maxBackups: 10
  maxAge: 30
  compress: true

accesslog:
  filePath: /logs/access.log
  format: common # json
  bufferingSize: 50
  filters:
    statusCodes:
      - 200-299
      - 400-599
  fields:
    headers:
      names:
        User-Agent: keep
