/logs/access.log {
  daily
  rotate 30
  size 10M
  create 0640 root root

  dateext
  dateformat .%Y-%m-%d
  # _%H-%M-%S

  compress
  delaycompress

  missingok
  notifempty

  sharedscripts
  postrotate
    kill -USR1 1
  endscript
}
