/logs/access.log {
  # daily # TODO: uncomment
  rotate 30
  size 10M
  create 0640 root root

  dateext
  # TODO: comment partial
  dateformat .%Y-%m-%d_%H-%M-%S

  compress
  delaycompress

  missingok
  notifempty

  sharedscripts
  postrotate
    kill -USR1 1
  endscript
}
